import { CheckCircle2, Clock3 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '../../components/common/Badge'
import { Card } from '../../components/common/Card'

const reviews = [{ id: 'REV-204', title: 'Refund exception response', agent: 'Billing Agent', status: 'Awaiting review' }, { id: 'REV-203', title: 'Enterprise SSO guidance', agent: 'Technical Agent', status: 'Approved' }]

export function ReviewsPage() {
  return <div className="mx-auto max-w-5xl space-y-6"><div><h1 className="text-2xl font-extrabold text-ink">Reviews</h1><p className="mt-1 text-sm text-slate-500">Review agent-generated responses before they reach customers.</p></div><div className="grid gap-4">{reviews.map((review) => <Link to={`/reviews/${review.id}`} key={review.id}><Card className="flex items-center justify-between gap-4 p-5 transition hover:border-brand-200 hover:shadow-md"><div className="flex items-start gap-4"><span className={`rounded-xl p-2.5 ${review.status === 'Approved' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}`}>{review.status === 'Approved' ? <CheckCircle2 className="h-5 w-5" /> : <Clock3 className="h-5 w-5" />}</span><div><p className="text-xs font-bold text-brand-600">{review.id}</p><h2 className="mt-1 font-bold text-slate-800">{review.title}</h2><p className="mt-1 text-xs text-slate-500">Generated by {review.agent}</p></div></div><Badge tone={review.status === 'Approved' ? 'green' : 'amber'}>{review.status}</Badge></Card></Link>)}</div></div>
}
