import { ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Ticket } from '../../types/ticket'
import { Card } from '../common/Card'
import { EmptyState } from '../common/EmptyState'
import { PriorityBadge, StatusBadge } from '../tickets/TicketBadges'

export function RecentTicketsTable({ tickets }: { tickets: Ticket[] }) {
  return <Card className="overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4 sm:px-6"><div><h2 className="font-bold text-ink">Recent tickets</h2><p className="mt-1 text-xs text-slate-500">Latest activity across your queues</p></div><Link to="/tickets" className="inline-flex items-center gap-1 text-sm font-bold text-brand-600 hover:text-brand-700">View all <ArrowRight className="h-4 w-4" /></Link></div>{tickets.length === 0 ? <EmptyState title="No tickets yet" message="New support requests will appear here as soon as they arrive." /> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b bg-slate-50/70 text-[11px] font-bold uppercase tracking-wider text-slate-500"><th className="px-6 py-3">Ticket</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Status</th><th className="px-6 py-3 text-right">Created</th></tr></thead><tbody className="divide-y">{tickets.map((ticket) => <tr key={ticket.id} className="transition hover:bg-slate-50"><td className="px-6 py-4"><Link to={`/tickets/${ticket.id}`} className="block max-w-xs"><span className="block text-xs font-bold text-brand-600">{ticket.id}</span><span className="mt-0.5 block truncate text-sm font-semibold text-slate-800">{ticket.title}</span></Link></td><td className="px-4 py-4"><span className="text-sm font-medium text-slate-700">{ticket.customer || 'Backend ticket'}</span><span className="block text-xs text-slate-400">{ticket.category || 'Uncategorized'}</span></td><td className="px-4 py-4"><PriorityBadge priority={ticket.priority} /></td><td className="px-4 py-4"><StatusBadge status={ticket.status} /></td><td className="px-6 py-4 text-right text-xs text-slate-500">{new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(ticket.createdAt))}</td></tr>)}</tbody></table></div>}</Card>
}
